FROM haproxy:1.8-alpine                                                                                                                                                                                         
COPY docker-entrypoint.sh /                                                                                                                                                                                     
ENTRYPOINT ["/docker-entrypoint.sh"]                                                                                                                                                                            
CMD ["haproxy", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]                                                                                                                                                     
                                                                                                                                                                                                                
RUN apk add --no-cache python3 &&\                                                                                                                                                                              
    pip3 install --no-cache-dir dnspython                                                                                                                                                                       
                                                                                                                                                                                                                
                                                                                                                                                                                                                
ENV LISTEN=:100 \                                                                                                                                                                                               
    TALK=talk:100                                                                                                                                                                                               
                                                                                                                                                                                                                
# Metadata                                                                                                                                                                                                      
ARG VCS_REF                                                                                                                                                                                                     
ARG BUILD_DATE                                                                                                                                                                                                  
LABEL org.label-schema.schema-version="1.0" \                                                                                                                                                                   
      org.label-schema.vendor=Tecnativa \                                                                                                                                                                       
      org.label-schema.license=Apache-2.0 \                                                                                                                                                                     
      org.label-schema.build-date="$BUILD_DATE" \                                                                                                                                                               
      org.label-schema.vcs-ref="$VCS_REF" \                                                                                                                                                                     
      org.label-schema.vcs-url="https://github.com/Tecnativa/docker-tcp-proxy"                                                                                                                                  
